import React from "react";
/**
 * Home: The Landing page of the web app
 * @return {JSX.Element} The JSX Code for the Home Page
 */

import type { NextPage } from "next";
import Head from "next/head";
import Header from "./components/Header";
import { Container } from "@mui/material";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Steigen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Container>
          <h1>Side for Steigen</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque dolor
            adipisci, quia alias illum, molestias quisquam, excepturi quidem
            nulla deleniti architecto itaque suscipit nobis nostrum quasi ipsum.
            Tempore perferendis similique obcaecati eveniet deserunt provident
            maiores explicabo, ut natus placeat ipsa. Odio, corporis illum
            eligendi incidunt ullam praesentium iste repudiandae hic.
          </p>
        </Container>
      </main>
    </div>
  );
};

export default Home;
